config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :static_pages
  resources :items
  resources :lists
  
  root 'static_pages#home'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :lists
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.create(list_params)
    redirect_to lists_path
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  def edit
    @list = List.find(params[:id])
  end
  
  def update
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @user = current_user

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="main-footer">
  <p>copyright &copy; 2016 norman chan</p>
</footer>

app/views/layouts/_header.html.erb
<div class="container">
  <div class="logo">
    <h1>ToDo Man</h1>
  </div>
  <div class="sub-heading">
    <p>The only todo list you need</p>
  </div>
  <div class="nav-bar">
    <% if user_signed_in? %>
    <ul>
      <li><%= link_to "profile" %></li>
      <li><%= link_to "todos", lists_path %></li>
      <li><%= link_to "log out", destroy_user_session_path, method: :delete %></li>
      <li>Signed in as: <%= current_user.email %></li>
    <% else %>
      <li><%= link_to "sign in" %></li>
    <% end %>
   </ul>
  </div>
</div>

app/views/layouts/_user_info.html.erb
<h1><%= current_user.email %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href="https://fonts.googleapis.com/css?family=Lobster|Questrial" rel="stylesheet">
  <title>Todoman</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/lists/index.html.erb
<div class="wrapper">
 <div class="container">

    <div class="main-heading">
      <h1>ToDo</h1>
      <div class="hr">
        <hr>
      </div>
    </div>
    <div class="add-item">
      <%= link_to "add item", new_list_path %>
    </div>
    <div class="todo-list">
      <ul>
      <% @lists.each do |list| %>
        <li>
          <%= list.name %>
          <%= link_to "Delete", list, method: :delete %>
          <%= link_to "Edit", edit_list_path(list) %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <div class="todo-form">
    <h1>ToDo</h1>
    <%= form_for @list do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/static_pages/home.html.erb
<% if user_signed_in? %>
  <%= render 'layouts/user_info' %>
<% else %>
  <%= link_to 'Sign in', new_user_session_path %>
  <%= link_to 'Sign up', new_user_registration_path %>
<% end %>

app/views/users/index.html.erb
<h1>All Users</h1>
<% @users.each do |user| %>
  <%= link_to user.email, user %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome <%= @user.email %></h1>